import jsPDF from 'jspdf';

// ─── Quote PDF ────────────────────────────────────────────────────────────────

export interface QuoteLineItemData {
  description: string;
  price: number;
}

export interface QuoteData {
  quoteNumber: string;
  date: string;
  customerName: string;
  customerEmail?: string;
  customerPhone?: string;
  petName?: string;
  lineItems: QuoteLineItemData[];
  totalAmount: number;
  notes?: string;
  businessName?: string;
}

export function generateQuotePDF(data: QuoteData): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Colors
  const primaryColor: [number, number, number] = [45, 156, 219]; // Teal
  const accentColor: [number, number, number] = [242, 153, 74];  // Orange
  const darkColor: [number, number, number] = [17, 24, 39];       // Gray 900
  const grayColor: [number, number, number] = [107, 114, 128];    // Gray 500

  // Header – Business Name
  doc.setFontSize(24);
  doc.setTextColor(...primaryColor);
  doc.text(data.businessName || 'BarkBook', 20, 25);

  doc.setFontSize(10);
  doc.setTextColor(...grayColor);
  doc.text('Professional Dog Grooming Services', 20, 32);

  // Quote Title
  doc.setFontSize(28);
  doc.setTextColor(...darkColor);
  doc.text('QUOTE', pageWidth - 20, 25, { align: 'right' });

  doc.setFontSize(10);
  doc.setTextColor(...grayColor);
  doc.text(`#${data.quoteNumber}`, pageWidth - 20, 32, { align: 'right' });

  // Separator
  doc.setDrawColor(...primaryColor);
  doc.setLineWidth(0.5);
  doc.line(20, 40, pageWidth - 20, 40);

  // Date
  let y = 55;
  doc.setFontSize(10);
  doc.setTextColor(...grayColor);
  doc.text('Quote Date:', 20, y);
  doc.setTextColor(...darkColor);
  doc.text(data.date, 60, y);

  // Quote For
  y = 80;
  doc.setFontSize(12);
  doc.setTextColor(...primaryColor);
  doc.text('QUOTE FOR', 20, y);

  y += 10;
  doc.setFontSize(11);
  doc.setTextColor(...darkColor);
  doc.text(data.customerName, 20, y);

  if (data.customerEmail) {
    y += 6;
    doc.setFontSize(10);
    doc.setTextColor(...grayColor);
    doc.text(data.customerEmail, 20, y);
  }
  if (data.customerPhone) {
    y += 6;
    doc.text(data.customerPhone, 20, y);
  }
  if (data.petName) {
    y += 10;
    doc.setFontSize(10);
    doc.setTextColor(...grayColor);
    doc.text('Pet:', 20, y);
    doc.setTextColor(...darkColor);
    doc.text(data.petName, 60, y);
  }

  // Line items table header
  y = 130;
  doc.setFillColor(...primaryColor);
  doc.rect(20, y - 5, pageWidth - 40, 10, 'F');

  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255);
  doc.text('Service / Description', 25, y);
  doc.text('Amount', pageWidth - 25, y, { align: 'right' });

  // Line items
  y += 12;
  data.lineItems.forEach((item, i) => {
    if (i % 2 === 1) {
      doc.setFillColor(248, 249, 250);
      doc.rect(20, y - 5, pageWidth - 40, 10, 'F');
    }
    doc.setTextColor(...darkColor);
    doc.setFontSize(10);
    doc.text(item.description, 25, y);

    const formatted = new Intl.NumberFormat('en-GB', {
      style: 'currency',
      currency: 'GBP',
    }).format(item.price);
    doc.text(formatted, pageWidth - 25, y, { align: 'right' });
    y += 12;
  });

  // Separator
  doc.setDrawColor(229, 231, 235);
  doc.line(20, y, pageWidth - 20, y);

  // Total
  y += 12;
  const formattedTotal = new Intl.NumberFormat('en-GB', {
    style: 'currency',
    currency: 'GBP',
  }).format(data.totalAmount);

  doc.setFontSize(14);
  doc.setTextColor(...primaryColor);
  doc.text('TOTAL', 25, y);
  doc.setTextColor(...accentColor);
  doc.setFontSize(16);
  doc.text(formattedTotal, pageWidth - 25, y, { align: 'right' });

  // Notes
  if (data.notes) {
    y += 20;
    doc.setFontSize(10);
    doc.setTextColor(...grayColor);
    doc.text('Notes:', 20, y);
    y += 6;
    doc.setTextColor(...darkColor);
    const lines = doc.splitTextToSize(data.notes, pageWidth - 40);
    doc.text(lines, 20, y);
  }

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 20;
  doc.setFontSize(9);
  doc.setTextColor(...grayColor);
  doc.text('This quote is valid for 30 days from the date above.', pageWidth / 2, footerY, { align: 'center' });
  doc.text('Generated by BarkBook', pageWidth / 2, footerY + 6, { align: 'center' });

  return doc;
}

export function downloadQuotePDF(data: QuoteData): void {
  const doc = generateQuotePDF(data);
  doc.save(`quote-${data.quoteNumber}.pdf`);
}

// ─── Invoice PDF ──────────────────────────────────────────────────────────────

interface InvoiceData {
  invoiceNumber: string;
  date: string;
  dueDate: string;
  customerName: string;
  customerEmail?: string;
  customerPhone?: string;
  petName?: string;
  service: string;
  price: number;
  businessName?: string;
}

export function generateInvoicePDF(data: InvoiceData): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Colors
  const primaryColor: [number, number, number] = [45, 156, 219]; // Teal
  const accentColor: [number, number, number] = [242, 153, 74]; // Orange
  const darkColor: [number, number, number] = [17, 24, 39]; // Gray 900
  const grayColor: [number, number, number] = [107, 114, 128]; // Gray 500
  
  // Header - Business Name
  doc.setFontSize(24);
  doc.setTextColor(...primaryColor);
  doc.text(data.businessName || 'BarkBook', 20, 25);
  
  doc.setFontSize(10);
  doc.setTextColor(...grayColor);
  doc.text('Professional Dog Grooming Services', 20, 32);
  
  // Invoice Title
  doc.setFontSize(28);
  doc.setTextColor(...darkColor);
  doc.text('INVOICE', pageWidth - 20, 25, { align: 'right' });
  
  // Invoice Number
  doc.setFontSize(10);
  doc.setTextColor(...grayColor);
  doc.text(`#${data.invoiceNumber}`, pageWidth - 20, 32, { align: 'right' });
  
  // Line separator
  doc.setDrawColor(...primaryColor);
  doc.setLineWidth(0.5);
  doc.line(20, 40, pageWidth - 20, 40);
  
  // Dates section
  let y = 55;
  doc.setFontSize(10);
  doc.setTextColor(...grayColor);
  doc.text('Invoice Date:', 20, y);
  doc.text('Due Date:', 20, y + 7);
  
  doc.setTextColor(...darkColor);
  doc.text(data.date, 60, y);
  doc.text(data.dueDate, 60, y + 7);
  
  // Bill To section
  y = 80;
  doc.setFontSize(12);
  doc.setTextColor(...primaryColor);
  doc.text('BILL TO', 20, y);
  
  y += 10;
  doc.setFontSize(11);
  doc.setTextColor(...darkColor);
  doc.text(data.customerName, 20, y);
  
  if (data.customerEmail) {
    y += 6;
    doc.setFontSize(10);
    doc.setTextColor(...grayColor);
    doc.text(data.customerEmail, 20, y);
  }
  
  if (data.customerPhone) {
    y += 6;
    doc.text(data.customerPhone, 20, y);
  }
  
  // Pet info if available
  if (data.petName) {
    y += 10;
    doc.setFontSize(10);
    doc.setTextColor(...grayColor);
    doc.text('Pet:', 20, y);
    doc.setTextColor(...darkColor);
    doc.text(data.petName, 60, y);
  }
  
  // Services table header
  y = 130;
  doc.setFillColor(...primaryColor);
  doc.rect(20, y - 5, pageWidth - 40, 10, 'F');
  
  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255);
  doc.text('Service', 25, y);
  doc.text('Amount', pageWidth - 25, y, { align: 'right' });
  
  // Service row
  y += 15;
  doc.setTextColor(...darkColor);
  doc.text(data.service, 25, y);
  
  // Format price
  const formattedPrice = new Intl.NumberFormat('en-GB', {
    style: 'currency',
    currency: 'GBP',
  }).format(data.price);
  doc.text(formattedPrice, pageWidth - 25, y, { align: 'right' });
  
  // Separator line
  y += 10;
  doc.setDrawColor(229, 231, 235);
  doc.line(20, y, pageWidth - 20, y);
  
  // Total
  y += 15;
  doc.setFontSize(14);
  doc.setTextColor(...primaryColor);
  doc.text('TOTAL', 25, y);
  doc.setTextColor(...accentColor);
  doc.setFontSize(16);
  doc.text(formattedPrice, pageWidth - 25, y, { align: 'right' });
  
  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 20;
  doc.setFontSize(9);
  doc.setTextColor(...grayColor);
  doc.text('Thank you for your business!', pageWidth / 2, footerY, { align: 'center' });
  doc.text('Generated by BarkBook', pageWidth / 2, footerY + 6, { align: 'center' });
  
  return doc;
}

export function downloadInvoicePDF(data: InvoiceData): void {
  const doc = generateInvoicePDF(data);
  doc.save(`invoice-${data.invoiceNumber}.pdf`);
}

export function getInvoicePDFBlob(data: InvoiceData): Blob {
  const doc = generateInvoicePDF(data);
  return doc.output('blob');
}
